2019/07/01 20:37:01 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://recapcha/index.php?r=site/login
---
2019/07/01 21:08:26 [error] [exception.CException] CException: Alias "ext.yiiReCaptcha.ReCaptchaValidator" is invalid. Make sure it points to an existing PHP file and the file is readable. in /Users/pro/projects/recapcha/framework/YiiBase.php:330
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('ext.yiiReCaptch...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('ext.yiiReCaptch...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:08:56 [error] [exception.CException] CException: Alias "ext.yiiReCaptcha.ReCaptchaValidator" is invalid. Make sure it points to an existing PHP file and the file is readable. in /Users/pro/projects/recapcha/framework/YiiBase.php:330
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('ext.yiiReCaptch...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('ext.yiiReCaptch...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:09:28 [error] [exception.CException] CException: Alias "ext.yiiReCaptcha.ReCaptchaValidator" is invalid. Make sure it points to an existing PHP file and the file is readable. in /Users/pro/projects/recapcha/framework/YiiBase.php:330
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('ext.yiiReCaptch...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('ext.yiiReCaptch...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:09:29 [error] [exception.CException] CException: Alias "ext.yiiReCaptcha.ReCaptchaValidator" is invalid. Make sure it points to an existing PHP file and the file is readable. in /Users/pro/projects/recapcha/framework/YiiBase.php:330
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('ext.yiiReCaptch...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('ext.yiiReCaptch...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:09:30 [error] [exception.CException] CException: Alias "ext.yiiReCaptcha.ReCaptchaValidator" is invalid. Make sure it points to an existing PHP file and the file is readable. in /Users/pro/projects/recapcha/framework/YiiBase.php:330
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('ext.yiiReCaptch...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('ext.yiiReCaptch...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:10:59 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:00 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:00 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:00 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:01 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:01 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:01 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/01 21:11:01 [error] [exception.CException] CException: Alias "extensions.ReCaptchaValidator" is invalid. Make sure it points to an existing directory or file. in /Users/pro/projects/recapcha/framework/YiiBase.php:355
Stack trace:
#0 /Users/pro/projects/recapcha/framework/validators/CValidator.php(174): YiiBase::import('extensions.ReCa...', true)
#1 /Users/pro/projects/recapcha/framework/base/CModel.php(287): CValidator::createValidator('extensions.ReCa...', Object(ContactForm), Array, Array)
#2 /Users/pro/projects/recapcha/framework/base/CModel.php(260): CModel->createValidators()
#3 /Users/pro/projects/recapcha/framework/base/CModel.php(547): CModel->getValidators()
#4 /Users/pro/projects/recapcha/framework/web/widgets/CActiveForm.php(567): CModel->getSafeAttributeNames()
#5 /Users/pro/projects/recapcha/protected/views/site/contact.php(38): CActiveForm->errorSummary(Object(ContactForm))
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#7 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#9 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#10 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#11 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#12 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#13 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#14 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#16 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/
---
2019/07/02 05:14:05 [error] [exception.Error] Error: Call to undefined function mcrypt_encrypt() in /Users/pro/projects/recapcha/protected/extensions/ReCaptcha.php:225
Stack trace:
#0 /Users/pro/projects/recapcha/protected/extensions/ReCaptcha.php(170): ReCaptcha->encryptAes('{"session_id":"...', '\xE4Z\xD0,"E\xDA\xDD\x8E\x8D\x1C'o)\x07...')
#1 /Users/pro/projects/recapcha/protected/extensions/ReCaptcha.php(142): ReCaptcha->encryptData('{"session_id":"...')
#2 /Users/pro/projects/recapcha/protected/extensions/ReCaptcha.php(81): ReCaptcha->createSecureToken('s0tl5bbthv6mhi2...')
#3 /Users/pro/projects/recapcha/framework/web/CBaseController.php(182): ReCaptcha->run()
#4 /Users/pro/projects/recapcha/protected/views/site/contact.php(79): CBaseController->widget('application.ext...', Array)
#5 /Users/pro/projects/recapcha/framework/web/CBaseController.php(126): require('/Users/pro/proj...')
#6 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', Array, true)
#7 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', Array, true)
#8 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('contact', Array, true)
#9 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#10 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#11 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('contact')
#15 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#16 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/index.php/site/contact
HTTP_REFERER=http://recapcha/index.php/site/contact
---
2019/07/02 21:08:18 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://recapcha/index.php/site/page?view=about
---
2019/07/10 18:35:03 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://recapcha/
---
2019/07/10 18:49:38 [error] [exception.ParseError] ParseError: syntax error, unexpected '$script' (T_VARIABLE) in /Users/pro/projects/recapcha/protected/views/site/test.php:9
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Users/pro/proj...', NULL, true)
#1 /Users/pro/projects/recapcha/framework/web/CController.php(872): CBaseController->renderFile('/Users/pro/proj...', NULL, true)
#2 /Users/pro/projects/recapcha/framework/web/CController.php(785): CController->renderPartial('test', NULL, true)
#3 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(116): CController->render('test')
#4 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionTest()
#5 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /Users/pro/projects/recapcha/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /Users/pro/projects/recapcha/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): CController->run('test')
#9 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test')
#10 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#11 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/index.php/site/test
---
2019/07/10 19:03:37 [error] [php] Undefined variable: script (/Users/pro/projects/recapcha/protected/views/site/test.php:3)
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CController.php(872): SiteController->renderFile()
#1 /Users/pro/projects/recapcha/framework/web/CController.php(785): SiteController->renderPartial()
#2 /Users/pro/projects/recapcha/protected/controllers/SiteController.php(116): SiteController->render()
#3 /Users/pro/projects/recapcha/framework/web/actions/CInlineAction.php(49): SiteController->actionTest()
#4 /Users/pro/projects/recapcha/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /Users/pro/projects/recapcha/framework/web/CController.php(286): SiteController->runAction()
#6 /Users/pro/projects/recapcha/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(282): SiteController->run()
#8 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /Users/pro/projects/recapcha/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/test
in /Users/pro/projects/recapcha/protected/views/site/test.php (3)
in /Users/pro/projects/recapcha/protected/controllers/SiteController.php (116)
in /Users/pro/projects/recapcha/index.php (13)
2019/07/10 19:19:57 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2019/07/10 19:21:42 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2019/07/10 19:46:49 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "favicon.ico". in /Users/pro/projects/recapcha/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/pro/projects/recapcha/framework/web/CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 /Users/pro/projects/recapcha/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/pro/projects/recapcha/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2019/07/22 11:27:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-start.loc/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii-start.loc/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii-start.loc/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii-start.loc/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(472): CModule->getComponent('db')
#4 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(512): MigrateCommand->getMigrationHistory(-1)
#6 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 /var/www/yii-start.loc/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 /var/www/yii-start.loc/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 /var/www/yii-start.loc/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 /var/www/yii-start.loc/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#12 /var/www/yii-start.loc/framework/yiic.php(33): CApplication->run()
#13 /var/www/yii-start.loc/protected/yiic.php(7): require_once('/var/www/yii-st...')
#14 /var/www/yii-start.loc/protected/yiic(4): require_once('/var/www/yii-st...')
#15 {main}
---
2019/07/22 11:33:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-start.loc/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii-start.loc/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii-start.loc/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii-start.loc/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(472): CModule->getComponent('db')
#4 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(512): MigrateCommand->getMigrationHistory(-1)
#6 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 /var/www/yii-start.loc/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 /var/www/yii-start.loc/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 /var/www/yii-start.loc/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 /var/www/yii-start.loc/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#12 /var/www/yii-start.loc/framework/yiic.php(33): CApplication->run()
#13 /var/www/yii-start.loc/protected/yiic.php(7): require_once('/var/www/yii-st...')
#14 /var/www/yii-start.loc/protected/yiic(4): require_once('/var/www/yii-st...')
#15 {main}
---
2019/07/22 11:36:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-start.loc/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii-start.loc/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii-start.loc/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii-start.loc/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(472): CModule->getComponent('db')
#4 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(512): MigrateCommand->getMigrationHistory(-1)
#6 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 /var/www/yii-start.loc/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 /var/www/yii-start.loc/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 /var/www/yii-start.loc/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 /var/www/yii-start.loc/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#12 /var/www/yii-start.loc/framework/yiic.php(33): CApplication->run()
#13 /var/www/yii-start.loc/protected/yiic.php(7): require_once('/var/www/yii-st...')
#14 /var/www/yii-start.loc/protected/yiic(4): require_once('/var/www/yii-st...')
#15 {main}
---
2019/07/22 11:38:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /var/www/yii-start.loc/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/yii-start.loc/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/yii-start.loc/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/yii-start.loc/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(472): CModule->getComponent('db')
#4 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(512): MigrateCommand->getMigrationHistory(-1)
#6 /var/www/yii-start.loc/framework/cli/commands/MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 /var/www/yii-start.loc/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 /var/www/yii-start.loc/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 /var/www/yii-start.loc/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 /var/www/yii-start.loc/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#12 /var/www/yii-start.loc/framework/yiic.php(33): CApplication->run()
#13 /var/www/yii-start.loc/protected/yiic.php(7): require_once('/var/www/yii-st...')
#14 /var/www/yii-start.loc/protected/yiic(4): require_once('/var/www/yii-st...')
#15 {main}
---
2019/07/22 11:40:50 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii_start.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2019/08/08 12:47:29 [error] [php] date() expects at least 1 parameter, 0 given (/var/www/yii-start.loc/protected/controllers/SiteController.php:117)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#2 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#3 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#4 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#6 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/test
in /var/www/yii-start.loc/protected/controllers/SiteController.php (117)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 12:53:17 [error] [php] date() expects at least 1 parameter, 0 given (/var/www/yii-start.loc/protected/controllers/SiteController.php:117)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#2 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#3 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#4 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#6 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/test
in /var/www/yii-start.loc/protected/controllers/SiteController.php (117)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 12:53:40 [error] [php] date_add() expects exactly 2 parameters, 0 given (/var/www/yii-start.loc/protected/controllers/SiteController.php:117)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#2 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#3 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#4 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#6 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/test
in /var/www/yii-start.loc/protected/controllers/SiteController.php (117)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 12:53:47 [error] [php] date() expects at least 1 parameter, 0 given (/var/www/yii-start.loc/protected/controllers/SiteController.php:117)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#2 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#3 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#4 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#6 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/test
in /var/www/yii-start.loc/protected/controllers/SiteController.php (117)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 12:59:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view
---
2019/08/08 13:00:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view,php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view,php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view,php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view,...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view,php
---
2019/08/08 13:00:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:00:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:00:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:01:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:01:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:01:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:01:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test_view.php".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('test_view.php')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('test_view.php')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/test_view....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/test_view.php
---
2019/08/08 13:02:00 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(4): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(130): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (130)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:02:18 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(4): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(130): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (130)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:02:19 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(4): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(130): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (130)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:05:05 [error] [php] Undefined variable: model (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:05:06 [error] [php] Undefined variable: model (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:07:48 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(3): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(129): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (3)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (129)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:07:49 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(3): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(129): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (3)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (129)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:07:56 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(3): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(129): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (3)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (129)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:08:07 [error] [php] include(Post.php): failed to open stream: No such file or directory (/var/www/yii-start.loc/framework/YiiBase.php:463)
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/test_view.php(3): spl_autoload_call()
#1 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require()
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#4 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#5 /var/www/yii-start.loc/protected/controllers/SiteController.php(129): SiteController->render()
#6 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#7 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#9 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#13 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (3)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (129)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:12:11 [error] [php] Trying to get property of non-object (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:12:20 [error] [php] Array to string conversion (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:12:29 [error] [php] Array to string conversion (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:12:45 [error] [php] Undefined index: id (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:12:47 [error] [php] Undefined index: id (/var/www/yii-start.loc/protected/views/site/test_view.php:4)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (4)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:15:36 [error] [php] Object of class TblContent could not be converted to string (/var/www/yii-start.loc/protected/views/site/test_view.php:16)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(132): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionView()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/view
in /var/www/yii-start.loc/protected/views/site/test_view.php (16)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (132)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 13:39:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "bootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('bootstrap-socia...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('bootstrap-socia...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/bootstrap-...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/bootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:39:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "bootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('bootstrap-socia...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('bootstrap-socia...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/bootstrap-...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/bootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3C?%20var_dump(__DIR__);?%3E
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3C?%20var_dump(__DIR__);?%3E
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3C?%20var_dump(__DIR__);?%3E
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req<pre class='xdebug-var-dump' dir='ltr'><small>".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req<pre class='...')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req<pre class='...')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req<pre cl...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req%3Cpre%20class='xdebug-var-dump'%20dir='ltr'%3E%3Csmall%3E/var/www/yii-start.loc/protected/views/site/viewcont.php:24:%3C/small%3E%3Csmall%3Estring%3C/small%3E%20%3Cfont%20color='
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:40:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "req".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('req')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('req')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/req')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/req
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/imagebootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/imagebootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/imagebootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/imagebootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/imagebootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/imagebootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:41:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:42:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image/bootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image/bootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:42:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image/
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image/bootstrap-social.png".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image/bootstrap-social.png
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 13:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "requirements/image".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('requirements/im...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/requirements/image/
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 15:32:55 [error] [php] Undefined variable: item (/var/www/yii-start.loc/protected/views/site/viewcont.php:56)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(139): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionViewcont()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/viewcont
in /var/www/yii-start.loc/protected/views/site/viewcont.php (56)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (139)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 16:04:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:04:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:04:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:04:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:05:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:05:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "waypoints.js".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('waypoints.js')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('waypoints.js')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/waypoints....')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:10:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "protected".' in /var/www/yii-start.loc/framework/web/CController.php:486
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(270): CController->missingAction('protected')
#1 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('protected')
#2 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/protected/...')
#3 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#4 /var/www/yii-start.loc/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php/site/protected/components/jquery.waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 16:10:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "protected/components/jquery.waypoints.js".' in /var/www/yii-start.loc/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('protected/compo...')
#1 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/yii-start.loc/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/protected/components/jquery.waypoints.js
HTTP_REFERER=http://yii-start.loc/index.php/site/viewcont
---
2019/08/08 17:58:17 [error] [php] Undefined variable: cs (/var/www/yii-start.loc/protected/views/site/viewcont.php:45)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(139): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionViewcont()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/viewcont
in /var/www/yii-start.loc/protected/views/site/viewcont.php (45)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (139)
in /var/www/yii-start.loc/index.php (13)
2019/08/08 18:00:42 [error] [exception.CException] exception 'CException' with message 'SiteController and its behaviors do not have a method or closure named "registerJsFile".' in /var/www/yii-start.loc/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/viewcont.php(45): CComponent->__call('registerJsFile', Array)
#1 /var/www/yii-start.loc/protected/views/site/viewcont.php(45): SiteController->registerJsFile('/js/jquery.lazy...')
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require('/var/www/yii-st...')
#3 /var/www/yii-start.loc/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/yii-st...', Array, true)
#4 /var/www/yii-start.loc/framework/web/CController.php(872): CBaseController->renderFile('/var/www/yii-st...', Array, true)
#5 /var/www/yii-start.loc/framework/web/CController.php(785): CController->renderPartial('viewcont', Array, true)
#6 /var/www/yii-start.loc/protected/controllers/SiteController.php(139): CController->render('viewcont', Array)
#7 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionViewcont()
#8 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/yii-start.loc/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/yii-start.loc/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('viewcont')
#12 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/viewcont')
#13 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#14 /var/www/yii-start.loc/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/site/viewcont
---
2019/08/08 18:00:43 [error] [exception.CException] exception 'CException' with message 'SiteController and its behaviors do not have a method or closure named "registerJsFile".' in /var/www/yii-start.loc/framework/base/CComponent.php:266
Stack trace:
#0 /var/www/yii-start.loc/protected/views/site/viewcont.php(45): CComponent->__call('registerJsFile', Array)
#1 /var/www/yii-start.loc/protected/views/site/viewcont.php(45): SiteController->registerJsFile('/js/jquery.lazy...')
#2 /var/www/yii-start.loc/framework/web/CBaseController.php(126): require('/var/www/yii-st...')
#3 /var/www/yii-start.loc/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/yii-st...', Array, true)
#4 /var/www/yii-start.loc/framework/web/CController.php(872): CBaseController->renderFile('/var/www/yii-st...', Array, true)
#5 /var/www/yii-start.loc/framework/web/CController.php(785): CController->renderPartial('viewcont', Array, true)
#6 /var/www/yii-start.loc/protected/controllers/SiteController.php(139): CController->render('viewcont', Array)
#7 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionViewcont()
#8 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/yii-start.loc/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/yii-start.loc/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): CController->run('viewcont')
#12 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController('site/viewcont')
#13 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#14 /var/www/yii-start.loc/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/index.php/site/viewcont
---
2019/08/08 18:05:21 [error] [php] Undefined variable: data (/var/www/yii-start.loc/protected/views/site/viewcont.php:24)
Stack trace:
#0 /var/www/yii-start.loc/framework/web/CController.php(872): SiteController->renderFile()
#1 /var/www/yii-start.loc/framework/web/CController.php(785): SiteController->renderPartial()
#2 /var/www/yii-start.loc/protected/controllers/SiteController.php(139): SiteController->render()
#3 /var/www/yii-start.loc/framework/web/actions/CInlineAction.php(49): SiteController->actionViewcont()
#4 /var/www/yii-start.loc/framework/web/CController.php(308): CInlineAction->runWithParams()
#5 /var/www/yii-start.loc/framework/web/CController.php(286): SiteController->runAction()
#6 /var/www/yii-start.loc/framework/web/CController.php(265): SiteController->runActionWithFilters()
#7 /var/www/yii-start.loc/framework/web/CWebApplication.php(282): SiteController->run()
#8 /var/www/yii-start.loc/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/yii-start.loc/framework/base/CApplication.php(185): CWebApplication->processRequest()
#10 /var/www/yii-start.loc/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php/site/viewcont
in /var/www/yii-start.loc/protected/views/site/viewcont.php (24)
in /var/www/yii-start.loc/protected/controllers/SiteController.php (139)
in /var/www/yii-start.loc/index.php (13)
